# https://taskfile.dev

version: "3"

tasks:
  code:check:
    cmd: kurra format --check

  code:
    cmd: kurra format .

  pylode:
    cmds:
      - pylode -p supermodel -o index.html schemas/app.ttl
      - python -m http.server

  test:
    cmd: pyshacl -a -s schemas/app.ttl tests/app.ttl

  test:roads:
    cmd: pyshacl -a -s schemas/roads.ttl tests/roads.ttl
