# https://taskfile.dev

version: "3"

tasks:
  code:check:
    cmd: kurra format --check

  code:
    cmd: kurra format .

  pylode:
    cmds:
      - pylode -p supermodel -o index.html schema.ttl
      - python -m http.server

  test:
    cmd: pyshacl -s schema.ttl test.ttl
